
services:
  caddy:
    image: caddy
    container_name: ${PACKAGE_NAME}_caddy
    restart: always
    profiles:
      - prod
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'caddy validate --config /etc/caddy/Caddyfile']
      interval: 30s
      timeout: 5s
      retries: 3

  server:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: rafisharkar/${PACKAGE_NAME}:latest
    container_name: ${PACKAGE_NAME}_api
    profiles:
      - prod
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@db:5432/${PACKAGE_NAME}_db

      REDIS_HOST: redis-master
      REDIS_PORT: 6379

      BASE_URL: http://0.0.0.0:5000/api
      PORT: 5000

      # Cron Jobs Configuration
      FEATURED_YACHT_CRON_ENABLED: ${FEATURED_YACHT_CRON_ENABLED:-true}
      FEATURED_YACHT_CRON_SCHEDULE: ${FEATURED_YACHT_CRON_SCHEDULE:-0 0 * * *}
      FEATURED_YACHT_CRON_TIMEZONE: ${FEATURED_YACHT_CRON_TIMEZONE:-America/New_York}
      FEATURED_YACHT_ROTATION_DAYS: ${FEATURED_YACHT_ROTATION_DAYS:-7}
    ports:
      - '5000:5000'
    depends_on:
      db:
        condition: service_healthy
      redis-master:
        condition: service_healthy
    command: >
      sh -c "
        echo '🏁 Waiting for DB...';
        sleep 5;
        npx prisma migrate deploy;
        echo '🚀 Starting app...';
        pnpm start
      "
    volumes:
      - files-data:/app/uploads
      - temp-data:/app/tmp
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://0.0.0.0:5000/health']
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:15
    container_name: ${PACKAGE_NAME}_db
    restart: always
    profiles:
      - dev
      - prod
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${PACKAGE_NAME}_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5443:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: ${PACKAGE_NAME}_pgadmin
    restart: unless-stopped
    profiles:
      - prod
    environment:
      - PGADMIN_DEFAULT_EMAIL=${SUPER_ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${SUPER_ADMIN_PASS}
      - SCRIPT_NAME=/pgadmin
    ports:
      - '8123:80'
    depends_on:
      db:
        condition: service_healthy
      server:
        condition: service_healthy

  redis-master:
    image: redis:8.0
    container_name: ${PACKAGE_NAME}_redis-master
    profiles:
      - dev
      - prod
    command:
      [
        'redis-server',
        '--appendonly',
        'yes',
        '--bind',
        '0.0.0.0',
        '--protected-mode',
        'no',
      ]
    ports:
      - '22380:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always

  redis-replica:
    image: redis
    container_name: ${PACKAGE_NAME}_redis-replica
    profiles:
      - prod
    command:
      [
        'redis-server',
        '--replicaof',
        'redis-master',
        '6379',
        '--bind',
        '0.0.0.0',
        '--protected-mode',
        'no',
      ]
    ports:
      - '22381:6379'
    depends_on:
      - redis-master
    restart: always

volumes:
  db_data:
  files-data:
  temp-data:
  caddy_data:
  caddy_config:

networks:
  default:
    name: ${PACKAGE_NAME}_network
    labels:
      - 'project=${PACKAGE_NAME}'



